const STORIES = [
  {
    id: "three-little-pigs",
    art: "three-little-pigs",
    title: "The Three Little Pigs",
    subtitle: "A tale of straw, sticks, and good strong bricks",
    minutes: 3,
    tint: "#F7E9CD",
    excerpt: "Three brothers build three houses. Only one of them is built to last, and it is very glad of it when the wind starts blowing.",
    moral: "Take your time and do it properly. Good work keeps you safe.",
    pullAfter: 5,
    pull: "Little pig, little pig, let me come in!",
    body: [
      "Once upon a time there were three little pigs. One morning they hugged their mother goodbye and set off to build houses of their very own.",
      "The first little pig was in a hurry. He found a pile of golden straw and built his house in one afternoon. It was soft and it was quick. Then he sat down to play his flute.",
      "The second little pig found a bundle of sticks. He built his house by teatime and went outside to play his fiddle.",
      "The third little pig carried bricks. One brick, then another brick, then another. He worked all day and all week. His brothers laughed at him. The third little pig only smiled and kept building.",
      "Along came a hungry wolf. He knocked at the house of straw and called out in his big rumbly voice.",
      "The first little pig held the door tight. But the wolf huffed, and he puffed, and he blew the straw house away like dandelion fluff. Off ran the first little pig to his brother's house of sticks.",
      "Knock, knock. The wolf huffed, and he puffed, and away went the sticks, clattering down the lane. Off ran both little pigs, as fast as their trotters would carry them, to the house of bricks.",
      "The wolf came to the brick house last of all. He knocked. He huffed. He puffed. He huffed and puffed until his cheeks went pink and his eyes went round.",
      "But the bricks did not budge. Not one single brick.",
      "The wolf sat down in the garden, quite out of puff, and decided he would rather have soup at home. He went away down the road and never came back.",
      "Inside, the three little pigs made cocoa and toasted bread by the fire. And that night, in the strong little house that had taken so long to build, all three of them slept safe and warm."
    ]
  },
  {
    id: "goldilocks",
    art: "goldilocks",
    title: "Goldilocks and the Three Bears",
    subtitle: "Too hot, too cold, and just right",
    minutes: 3,
    tint: "#F2E3C9",
    excerpt: "A curious girl wanders into a little house in the woods and tries everything in it. Then the family who lives there comes home.",
    moral: "Ask before you borrow. Other people's things are theirs.",
    pullAfter: 6,
    pull: "Somebody has been sleeping in my bed &mdash; and she is still there!",
    body: [
      "Deep in the woods there was a little house, and in the little house lived three bears: a great big Papa Bear, a middle-sized Mama Bear, and a small wee Baby Bear.",
      "One morning they made porridge for breakfast. It was far too hot to eat, so the three bears went for a walk in the woods while it cooled.",
      "While they were out, a girl called Goldilocks came skipping along. She saw the little house. She peeped in the window. Then she opened the door and walked right in, which she should not have done at all.",
      "On the table were three bowls of porridge. Goldilocks tasted the great big bowl. Too hot! She tasted the middle bowl. Too cold! She tasted the small wee bowl. Just right &mdash; and she ate up every spoonful.",
      "Then she saw three chairs. The big chair was too hard. The middle chair was too soft. The small wee chair was just right, but when she wriggled and bounced, it broke into pieces underneath her.",
      "Goldilocks went upstairs and found three beds. The big bed was too lumpy. The middle bed was too squashy. The small wee bed was just right, and she was so sleepy that she curled up and fell fast asleep.",
      "Home came the three bears. Papa Bear looked at his bowl and rumbled, Somebody has been eating my porridge! Mama Bear said the same. And Baby Bear said, in a very small voice, Somebody has eaten mine all up.",
      "They looked at the chairs. They climbed the stairs. And there in the small wee bed was a girl with tangled golden hair, snoring softly.",
      "Goldilocks opened her eyes and saw three furry faces looking down at her. Oh my! She jumped out of bed, ran down the stairs, out of the door and all the way home through the trees.",
      "The three bears mended the little chair with glue and made fresh porridge. And Goldilocks never went into anybody's house again without knocking first."
    ]
  },
  {
    id: "little-red-hen",
    art: "little-red-hen",
    title: "The Little Red Hen",
    subtitle: "Who will help me bake the bread?",
    minutes: 2,
    tint: "#FBEFD5",
    excerpt: "The little red hen finds a grain of wheat and asks her friends for help. They are all far too comfortable to move.",
    moral: "Helping with the work means sharing in the treat.",
    pullAfter: 5,
    pull: "Not I, said the cat. Not I, said the dog. Not I, said the duck.",
    body: [
      "In a warm little farmyard lived a little red hen, a lazy cat, a sleepy dog, and a duck who liked to sit in the sun.",
      "One day the little red hen was scratching in the dust when she found a grain of wheat. Who will help me plant this wheat? she asked.",
      "Not I, said the cat. Not I, said the dog. Not I, said the duck. Then I shall plant it myself, said the little red hen. And she did.",
      "The wheat grew tall and golden. Who will help me cut the wheat? asked the little red hen. Not I, not I, not I. So she cut it herself, snip snip snip.",
      "Who will help me carry the wheat to the mill? Not I, not I, not I. So the little red hen carried it herself, all the way there and all the way back, with a sack of soft white flour.",
      "Who will help me bake the bread? Not I, said the cat, stretching. Not I, said the dog, yawning. Not I, said the duck, who had one eye shut.",
      "So the little red hen mixed the flour and kneaded the dough and lit the oven. Soon the whole farmyard smelled of warm fresh bread.",
      "The cat sat up. The dog opened both eyes. The duck waddled over very quickly indeed.",
      "Who will help me eat the bread? asked the little red hen.",
      "I will! said the cat. I will! said the dog. I will! said the duck.",
      "Oh no, said the little red hen. I planted it and cut it and carried it and baked it all by myself. And I shall eat it myself too.",
      "And she did &mdash; every crumb. The next time there was work to do, the cat and the dog and the duck were the first ones there."
    ]
  },
  {
    id: "tortoise-and-hare",
    art: "tortoise-and-hare",
    title: "The Tortoise and the Hare",
    subtitle: "A race that everybody was sure they knew the end of",
    minutes: 2,
    tint: "#EAF1E6",
    excerpt: "The fastest animal in the wood laughs at the slowest one. So the slowest one challenges him to a race.",
    moral: "Slow and steady wins the race.",
    pullAfter: 4,
    pull: "I shall just have a tiny nap, said the hare.",
    body: [
      "There was once a hare who could run faster than anyone. He never let anybody forget it.",
      "Look how slow you are, he laughed at the tortoise one morning. You go plod, plod, plod. I could run around the whole wood before you reached that tree.",
      "The tortoise thought about this for a little while. Then she said, Let us have a race.",
      "All the animals came to watch. A crow said, Ready, steady, GO! and the hare shot away in a puff of dust. The tortoise started walking. Plod. Plod. Plod.",
      "Very soon the hare was so far ahead that he could not see the tortoise at all. There was a shady tree by the path, and the grass underneath it was soft and cool.",
      "There is no hurry, said the hare to himself. I shall just have a tiny nap. He lay down, wriggled his nose, and fell fast asleep.",
      "The tortoise came around the corner. Plod. Plod. Plod. She saw the hare sleeping. She did not stop. She did not hurry either. She simply kept going, one foot after the other, all afternoon.",
      "A breeze rustled the leaves and the hare woke up with a jump. The sun had moved! He raced down the path, faster than he had ever run in his life.",
      "But there at the finishing line, with all the animals cheering around her, was the tortoise.",
      "How? gasped the hare.",
      "I never stopped, said the tortoise."
    ]
  },
  {
    id: "gingerbread-man",
    art: "gingerbread-man",
    title: "The Gingerbread Man",
    subtitle: "Run, run, as fast as you can",
    minutes: 2,
    tint: "#FAEBD3",
    excerpt: "A biscuit hops off the baking tray and out of the door, and half the countryside goes running after him.",
    moral: "A little care is worth more than a lot of running.",
    pullAfter: 3,
    pull: "Run, run, as fast as you can! You cannot catch me, I am the Gingerbread Man!",
    body: [
      "One morning a little old woman rolled out gingerbread dough and cut it into the shape of a man. She gave him currant eyes, a cherry smile, and three white icing buttons down his front. Then she popped him in the oven.",
      "When she opened the oven door, up jumped the Gingerbread Man and out he ran, straight across the kitchen floor.",
      "Stop! called the little old woman. Stop! called the little old man. But the Gingerbread Man laughed over his shoulder as he ran.",
      "He ran past a cow in the meadow. Stop, said the cow, you look delicious. The Gingerbread Man only ran faster, and the cow came running after.",
      "He ran past a horse and a barnful of hens and a boy carrying a rake, and every single one of them came running after too. What a long line they made, huffing down the lane.",
      "Then the Gingerbread Man came to a wide cold river, and he stopped, because gingerbread does not swim.",
      "A fox was sitting on the bank. I can carry you across, said the fox kindly. Hop onto my tail.",
      "So the Gingerbread Man hopped onto the fox's tail. The water grew deeper. Climb onto my back, said the fox. Then, Climb onto my nose, or you will get soggy.",
      "The Gingerbread Man climbed onto the fox's nose. The fox reached the far bank, tipped back his head &mdash; and snap!",
      "The clever fox had his supper, and the Gingerbread Man was never seen running again.",
      "The little old woman went home and baked a whole tray of gingerbread people. And do you know, she let them cool right down before she opened the door."
    ]
  },
  {
    id: "red-riding-hood",
    art: "red-riding-hood",
    title: "Little Red Riding Hood",
    subtitle: "Straight along the path, and no wandering",
    minutes: 3,
    tint: "#2E4139",
    excerpt: "A girl in a red cloak carries a basket through the woods to her grandmother, and meets somebody with very big teeth.",
    moral: "Stay on the path, and tell a grown-up when something feels wrong.",
    pullAfter: 6,
    pull: "Grandmother, what big teeth you have!",
    body: [
      "There was once a little girl who wore a red velvet cloak with a hood, so everybody called her Little Red Riding Hood.",
      "One morning her mother packed a basket with bread and honey. Take this to Grandmother, she said. She is poorly. Go straight along the path and do not wander.",
      "I will, said Little Red Riding Hood, and off she went into the green woods.",
      "Halfway there she met a wolf, standing among the trees with his tail low. Good morning, said the wolf, ever so politely. Where are you off to?",
      "To Grandmother's cottage, said Little Red Riding Hood, at the end of the path by the three oak trees.",
      "What lovely flowers there are over there, said the wolf, pointing away from the path. Your grandmother would love a bunch. And while Little Red Riding Hood was picking them, the wolf ran ahead on his long grey legs.",
      "When the girl arrived, Grandmother's door was open and Grandmother was in bed with the blanket pulled right up to her nose. But something was not right.",
      "Grandmother, what big ears you have, said Little Red Riding Hood.",
      "All the better to hear you with, said a growly voice.",
      "Grandmother, what big eyes you have.",
      "All the better to see you with.",
      "Grandmother, what big teeth you have!",
      "The wolf sprang up. But Little Red Riding Hood was quick, and she shouted as loudly as she could. A woodcutter working nearby heard her and came running with his axe over his shoulder, and the wolf took one look at him and bolted out of the window and away over the hills.",
      "And there was Grandmother, safe in the wardrobe where the wolf had shut her, cross but quite unhurt.",
      "They all sat down together and ate the bread and honey. And after that, Little Red Riding Hood stayed on the path every single time."
    ]
  },
  {
    id: "billy-goats-gruff",
    art: "billy-goats-gruff",
    title: "The Three Billy Goats Gruff",
    subtitle: "Trip trap, trip trap, over the bridge",
    minutes: 2,
    tint: "#DCE9EC",
    excerpt: "Three hungry goats want the sweet grass on the other side of the river. Underneath the bridge, something is listening.",
    moral: "Even the smallest one can be clever, and the biggest one can be brave.",
    pullAfter: 3,
    pull: "Who is that trip trapping over my bridge?",
    body: [
      "Once there were three billy goats, and they were all called Gruff. There was a little Billy Goat Gruff, a middle Billy Goat Gruff, and a great big Billy Goat Gruff with horns like tree branches.",
      "The grass on their side of the river was nibbled down to nothing. But on the other side, up the green hillside, the grass was long and sweet. To reach it they had to cross a little wooden bridge.",
      "And under that bridge lived a troll, with eyes like saucers and a nose like a poker.",
      "First went the little Billy Goat Gruff. Trip trap, trip trap. WHO is that trip trapping over my bridge? roared the troll.",
      "It is only me, said the little goat in a tiny voice. Please do not eat me. My brother is coming, and he is much bigger.",
      "The troll thought about that. Very well, be off with you.",
      "Next came the middle Billy Goat Gruff. Trip TRAP, trip TRAP. WHO is that trip trapping over my bridge?",
      "It is only me, said the middle goat. Do not eat me. My brother is coming, and he is bigger still.",
      "Bigger still? said the troll, licking his lips. Then off you go.",
      "Last of all came the great big Billy Goat Gruff. TRIP TRAP, TRIP TRAP, TRIP TRAP. The whole bridge shook.",
      "WHO is that trip trapping over MY bridge? roared the troll, climbing up.",
      "IT IS I, said the great big Billy Goat Gruff, and he lowered his enormous horns.",
      "The troll took one look, squeaked, and jumped off the bridge into the water, and the river carried him far away downstream.",
      "So the three Billy Goats Gruff crossed over to the sweet green hillside, where they ate and ate until they were so fat they could hardly walk home. Snip, snap, snout, this tale is told out."
    ]
  },
  {
    id: "chicken-little",
    art: "chicken-little",
    title: "Chicken Little",
    subtitle: "The day the sky fell down (or did it?)",
    minutes: 2,
    tint: "#CFE3EC",
    excerpt: "Something bonks Chicken Little on the head, and within five minutes the whole farmyard is running to tell the king.",
    moral: "Look properly before you worry. And look up, too.",
    pullAfter: 3,
    pull: "The sky is falling! I must go and tell the king!",
    body: [
      "Chicken Little was scratching for seeds under the big oak tree when something fell out of the sky and bonked her right on the head.",
      "Oh! said Chicken Little. Oh my goodness. The sky is falling! I must go and tell the king!",
      "Off she ran down the lane. On the way she met Henny Penny. Where are you going in such a rush? asked Henny Penny.",
      "The sky is falling, said Chicken Little. A piece of it fell on my head. I am going to tell the king.",
      "Then I shall come too, said Henny Penny.",
      "Next they met Ducky Lucky, and then Goosey Loosey, and then Turkey Lurkey, and every one of them said, Goodness me, the sky is falling! I shall come too. What a flapping, honking, gobbling crowd they made hurrying down the road.",
      "Then they met Foxy Loxy, who smiled a very wide smile. The king? he said. Why, the king lives just through those trees. Follow me and I shall show you the shortcut.",
      "But a wise old owl was sitting on the gate, and she had been watching the fox all morning. Wait, she said. Chicken Little, what exactly fell on your head?",
      "Chicken Little thought. It was small, she said. And hard. And brown.",
      "The owl looked up at the big oak tree, full of small hard brown acorns. And so did everybody else.",
      "Oh, said Chicken Little, going quite pink under her feathers.",
      "Foxy Loxy slipped away into the bushes with no supper at all. And the whole farmyard walked home together, laughing, under a sky that was exactly where it had always been."
    ]
  },
  {
    id: "boy-who-cried-wolf",
    art: "boy-who-cried-wolf",
    title: "The Boy Who Cried Wolf",
    subtitle: "A joke that stopped being funny",
    minutes: 2,
    tint: "#F4E6C8",
    excerpt: "A bored shepherd boy shouts wolf for fun, twice. On the third day, he is not joking.",
    moral: "Nobody believes a person who tells tales, even when they tell the truth.",
    pullAfter: 3,
    pull: "Wolf! Wolf! Come quickly, there is a wolf!",
    body: [
      "High on a green hillside above the village, a boy sat all day watching the sheep. It was a very important job. It was also, he thought, a very boring one.",
      "One morning he had an idea that made him giggle. He stood up, cupped his hands around his mouth, and shouted down the hill.",
      "Wolf! Wolf! Come quickly, there is a wolf!",
      "Up came the villagers, running and puffing, with sticks and buckets and one man still holding his breakfast. And there was no wolf at all. Only sheep, chewing grass, and a boy rolling about laughing.",
      "That was not kind, said the villagers, and they walked back down the hill.",
      "A few days later the boy was bored again. Wolf! he shouted. Wolf! Up came the villagers, running and puffing all over again. And again there was nothing but sheep and giggling.",
      "Do not call us again unless it is true, they said, and this time they were not smiling.",
      "Then one evening, when the sun was going down and the shadows grew long, something grey slipped out of the trees at the top of the hill. It had yellow eyes and it was watching the sheep.",
      "The boy jumped up. Wolf! he shouted. WOLF! Please, please come, there really is a wolf!",
      "Down in the village, the people heard him. They shook their heads and carried on with their supper. That boy, they said.",
      "Nobody came.",
      "The wolf chased the sheep all the way into the wood, and the boy sat down in the grass and cried real tears.",
      "The next morning an old woman found him. Why did nobody come? he asked her.",
      "Because, she said gently, nobody believes a person who tells tales &mdash; even when they are telling the truth.",
      "And from that day on, the boy only ever said what was so."
    ]
  },
  {
    id: "ugly-duckling",
    art: "ugly-duckling",
    title: "The Ugly Duckling",
    subtitle: "The little bird who was not a duck at all",
    minutes: 3,
    tint: "#E6EDE4",
    excerpt: "A big grey duckling does not look like his brothers and sisters, and he cannot think why. One spring morning, he finds out.",
    moral: "You may simply be growing into something you cannot see yet.",
    pullAfter: 7,
    pull: "He was not an ugly duckling at all. He never had been.",
    body: [
      "Down among the reeds at the edge of the pond, a mother duck sat on her nest, waiting.",
      "Crack, crack, crack. Out came five yellow ducklings, small and fluffy and exactly the same. Then the last and biggest egg gave a wobble, and out tumbled a duckling who was grey, and lanky, and not the same at all.",
      "The other ducks on the pond looked at him sideways. He is too big, they whispered. He is too grey. What an ugly duckling.",
      "His brothers and sisters would not play with him. The hens pecked at him and the farm cat laughed at him, and one sad autumn morning the grey duckling walked away from the pond to find somewhere he might fit.",
      "He walked a long way. He slept in the rushes. When winter came, the water froze at the edges and the wind was cold and he tucked his head under his wing and waited, because there was nothing else to do.",
      "But winters end. The ice melted and the sun came back, and the grey bird stretched wings that had somehow grown enormous while he slept.",
      "He flew. Right over the fields, all the way to a wide blue lake, where three beautiful white swans were gliding in the sunshine.",
      "They will chase me away, he thought. But he was lonely, so he swam towards them anyway with his head bowed low &mdash; and he saw himself in the still water.",
      "Looking back at him was a swan. A long white neck, soft white feathers, wide white wings. He was not an ugly duckling at all. He never had been. He had only been a swan who had not finished growing.",
      "The three swans came and touched their beaks to his, gently, the way swans do, and told him he was the finest of them all.",
      "And the big grey bird, who was not grey any more, tucked his head down and thought that he had never once dreamed of being this happy, back when he was the ugly duckling."
    ]
  }
];
